using System.Collections.Generic;

namespace Prt.App.Services;

/// <summary>
/// 界面词条表（中文 / English）。
/// <para>
/// 约定：键用「区域.名称」的点分小写形式；两套表的**键集合必须完全一致**——
/// 自检用例「界面词条中英一致」会逐键核对，缺条即失败。
/// 词条里的占位符用 <c>{0}</c> / <c>{1}</c>；排版用全角标点由中文表自行决定。
/// </para>
/// </summary>
internal static class Strings
{
    /// <summary>中文词条（基准表；英文缺条时回退到这里）。</summary>
    internal static readonly IReadOnlyDictionary<string, string> Zh =
        new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            // ───────────────────────── 通用 ─────────────────────────
            ["app.name"] = "PRT 阅读器",
            ["common.ok"] = "确定",
            ["common.cancel"] = "取消",
            ["common.close"] = "关闭",
            ["common.reset"] = "恢复默认",
            ["common.browse"] = "浏览…",
            ["common.refresh"] = "刷新",
            ["common.yes"] = "是",
            ["common.no"] = "否",

            // ───────────────────────── 标题栏 ─────────────────────────
            ["caption.minimize"] = "最小化",
            ["caption.maximize"] = "最大化",
            ["caption.restore"] = "还原",
            ["caption.close"] = "关闭",

            // ───────────────────────── 菜单：文件 ─────────────────────────
            ["menu.file"] = "文件(_F)",
            ["menu.file.new"] = "新建(_N)",
            ["menu.file.open"] = "打开(_O)…",
            ["menu.file.save"] = "保存(_S)",
            ["menu.file.saveas"] = "另存为(_A)…",
            ["menu.file.reload"] = "重新载入",
            ["menu.file.closetab"] = "关闭当前标签",
            ["menu.file.closeall"] = "关闭全部标签",
            ["menu.file.export.html"] = "导出为 HTML…",
            ["menu.file.export.markdown"] = "导出为 Markdown…",
            ["menu.file.export.text"] = "导出为纯文本…",
            ["menu.file.import.html"] = "从 HTML 新建文档…",
            ["menu.file.import.html.tip"] = "把网页或 Word 导出的 HTML 转成 PRT 文档（新标签打开）",
            ["menu.file.print"] = "打印…",
            ["menu.file.exit"] = "退出(_X)",

            // ───────────────────────── 菜单：编辑 ─────────────────────────
            ["menu.edit"] = "编辑(_E)",
            ["menu.edit.undo"] = "撤销",
            ["menu.edit.redo"] = "重做",
            ["menu.edit.cut"] = "剪切",
            ["menu.edit.copy"] = "复制",
            ["menu.edit.paste"] = "粘贴",
            ["menu.edit.selectline"] = "选中光标所在整行",
            ["menu.edit.find"] = "查找…",
            ["menu.edit.replace"] = "替换…",
            ["menu.edit.selectall"] = "全选",

            // ───────────────────────── 菜单：插入 / 视图 ─────────────────────────
            ["menu.insert"] = "插入(_I)",
            ["menu.insert.semantic"] = "语义框（13 类）",
            ["menu.insert.structure"] = "结构块",
            ["menu.insert.basic"] = "基础块",
            ["menu.view"] = "视图(_V)",
            ["menu.view.mode.editor"] = "仅源码编辑",
            ["menu.view.mode.split"] = "分栏（源码 + 视觉化编辑）",
            ["menu.view.mode.preview"] = "视觉化编辑",
            ["menu.view.outline"] = "显示目录面板",
            ["menu.view.problems"] = "显示诊断面板",
            ["menu.view.wordwrap"] = "编辑器自动换行",
            ["menu.view.zoomin"] = "放大",
            ["menu.view.zoomout"] = "缩小",
            ["menu.view.zoomreset"] = "重置缩放",
            ["menu.view.strict"] = "强制严格模式（忽略文档内 strict 声明）",

            // ───────────────────────── 菜单：主题 ─────────────────────────
            ["menu.theme"] = "主题(_T)",
            ["menu.theme.interface"] = "界面配色",
            ["menu.theme.interface.light"] = "浅色",
            ["menu.theme.interface.dark"] = "深色",
            ["menu.theme.preview"] = "预览主题（PRT 主题，标准第 12 章）",
            ["menu.theme.preview.follow"] = "跟随文档声明",
            ["menu.theme.preview.default"] = "default",
            ["menu.theme.preview.dark"] = "dark",
            ["menu.theme.preview.print"] = "print",
            ["menu.theme.preview.accessible"] = "accessible",

            // ───────────────────────── 菜单：设置 / 帮助 ─────────────────────────
            ["menu.settings"] = "设置(_S)",
            ["menu.settings.general"] = "总设置…",
            ["menu.settings.tutorial"] = "打开教程（内置）",
            ["menu.settings.authorguide"] = "打开作者指南（内置）",
            ["menu.help"] = "帮助(_H)",
            ["menu.help.sample"] = "打开示例文档…",
            ["menu.help.activation"] = "激活与授权…",
            ["menu.help.compliance"] = "符合性声明…",
            ["menu.help.security"] = "安全中心…",
            ["menu.help.shortcuts"] = "快捷键…",
            ["menu.help.about"] = "关于…",

            // ───────────────────────── 命令栏 ─────────────────────────
            ["toolbar.new"] = "新建",
            ["toolbar.new.tip"] = "新建文档（Ctrl+N）",
            ["toolbar.open"] = "打开",
            ["toolbar.open.tip"] = "打开文档（Ctrl+O）",
            ["toolbar.save"] = "保存",
            ["toolbar.save.tip"] = "保存（Ctrl+S）",
            ["toolbar.undo.tip"] = "撤销（Ctrl+Z）",
            ["toolbar.redo.tip"] = "重做（Ctrl+Y）",
            ["toolbar.find"] = "查找",
            ["toolbar.find.tip"] = "查找（Ctrl+F）",
            ["toolbar.replace"] = "替换",
            ["toolbar.replace.tip"] = "替换（Ctrl+H）",
            ["toolbar.mode.source"] = "源码",
            ["toolbar.mode.split"] = "分栏",
            ["toolbar.mode.preview"] = "视觉化",
            ["toolbar.outline"] = "目录",
            ["toolbar.outline.tip"] = "显示 / 隐藏目录面板",
            ["toolbar.problems"] = "诊断",
            ["toolbar.problems.tip"] = "显示 / 隐藏诊断面板",
            ["toolbar.export.html.tip"] = "导出为 HTML 文件",
            ["toolbar.export.markdown.tip"] = "导出为 Markdown 文件",
            ["toolbar.export.text"] = "纯文本",
            ["toolbar.export.text.tip"] = "导出为纯文本文件",
            ["toolbar.print"] = "打印",
            ["toolbar.print.tip"] = "打印（Ctrl+P）",

            // ───────────────────────── 面板 ─────────────────────────
            ["panel.outline"] = "目录",
            ["panel.problems"] = "诊断",

            // ───────────────────────── 状态栏 ─────────────────────────
            ["status.ready"] = "就绪",
            ["status.position"] = "行 {0}，列 {1}",
            ["status.chars"] = "{0} 字符",
            ["status.diagnostics"] = "错误 {0} · 警告 {1}",
            ["status.mode.editor"] = "源码",
            ["status.mode.split"] = "分栏",
            ["status.mode.preview"] = "视觉化",
            ["status.interface.dark"] = "界面配色：深色",
            ["status.interface.light"] = "界面配色：浅色",
            ["status.zoom"] = "缩放：{0}%",
            ["status.wordwrap.on"] = "编辑器已启用自动换行",
            ["status.wordwrap.off"] = "编辑器已关闭自动换行",
            ["status.strict.forced"] = "已强制严格模式：文档内的 strict 声明被忽略",
            ["status.strict.follow"] = "严格模式：遵循文档内 strict 声明（未声明时为严格）",
            ["status.previewtheme"] = "预览主题：{0}",
            ["status.previewtheme.follow"] = "预览主题：跟随文档声明",
            ["status.settings.applied"] = "设置已应用",
            ["status.settings.preview"] = "设置预览中（点「确定」保存）",
            ["status.settings.reverted"] = "已放弃本次设置改动",
            ["status.language.restart"] = "语言已切换，重启程序后完全生效",
            ["status.splash.updated"] = "启动界面图片已更新",
            ["status.splash.reset"] = "已恢复内置启动界面",
            ["status.print.done"] = "已送出打印",
            ["status.print.cancelled"] = "已取消打印",
            ["status.bundled.missing"] = "{0}——请确认安装目录下的「帮助」文件夹完整。",
            ["status.bundled.opened"] = "已打开内置{0}：{1}",
            ["status.bundled.switched"] = "已切换到已打开的{0}",
            ["doc.authorguide"] = "作者指南",
            ["doc.authorguide.missing"] = "未随程序找到《PRT 作者指南》文件",
            ["status.tutorial.opened"] = "已打开互动教程：左边选课，右边读、试、看效果",
            ["status.conformance"] = "PRT v{0} · EXT（不支持 COMP）",
            ["status.comp.degraded"] = " · 含 COMP 降级",

            // ───────────────────────── 设置窗口 ─────────────────────────
            ["settings.title"] = "设置",
            ["settings.footer"] = "改动会立刻生效（预览）；点「确定」保存，取消或直接关闭则恢复原样。",
            ["settings.tab.appearance"] = "外观",
            ["settings.tab.editor"] = "编辑",
            ["settings.tab.startup"] = "启动与语言",
            ["settings.interface"] = "界面配色",
            ["settings.interface.light"] = "浅色",
            ["settings.interface.dark"] = "深色",
            ["settings.interface.hint"] = "影响菜单、面板等程序自身的样子；预览区会跟随界面配色（文档里另有声明时以文档为准）。",
            ["settings.previewtheme"] = "文档外观（预览主题）",
            ["settings.previewtheme.follow"] = "跟随文档里的声明（未声明时跟随界面）",
            ["settings.previewtheme.default"] = "默认（浅色）",
            ["settings.previewtheme.dark"] = "深色",
            ["settings.previewtheme.print"] = "打印（黑白）",
            ["settings.previewtheme.accessible"] = "高可读性（无障碍）",
            ["settings.previewtheme.hint"] = "只影响文档显示的样子，不改动文档内容。",
            ["settings.zoom"] = "缩放",
            ["settings.wordwrap"] = "长行自动折行显示（不插入换行）",
            ["settings.strict"] = "严格校验收发（发现写法问题就报错）",
            ["settings.strict.hint"] = "默认按「尽量显示」处理：能看懂的照常显示，看不懂的原样保留。勾选后改为严格模式，遇到问题会直接报错，适合定稿前检查。",
            ["settings.viewmode"] = "默认显示方式",
            ["settings.viewmode.editor"] = "仅代码",
            ["settings.viewmode.split"] = "分栏",
            ["settings.viewmode.preview"] = "仅可视化",
            ["settings.viewmode.hint"] = "新建文档或打开程序时用哪种视图；工具栏与「视图」菜单里随时可以临时切换。",
            ["settings.splash.enable"] = "启动时显示启动界面",
            ["settings.splash.image"] = "启动界面图片",
            ["settings.splash.builtin"] = "内置图片",
            ["settings.splash.hint"] = "支持 PNG / JPG / BMP；建议使用 2:1 左右的横图（如 640×320）。图片会复制到程序所在文件夹，原文件删除或移动都不影响。",
            ["settings.language"] = "界面语言",
            ["settings.language.system"] = "跟随系统",
            ["settings.language.zh"] = "简体中文",
            ["settings.language.en"] = "English",
            ["settings.language.hint"] = "切换后菜单、对话框等在下一次启动时完全生效。",
            ["settings.defaultview.changed"] = "默认显示方式：{0}",
            ["settings.splash.failed"] = "启动图片设置失败：{0}",
            ["settings.save.failed"] = "设置未能保存：{0}",

            // ───────────────────────── 教程窗口 ─────────────────────────
            ["tutorial.title"] = "教程",
            ["tutorial.subtitle"] = "边做边学：左边选课，右边读、试、看效果",
            ["tutorial.lessons"] = "课程",
            ["tutorial.progress"] = "第 {0} / {1} 课",
            ["tutorial.snippet"] = "本课示例（可插入编辑器）",
            ["tutorial.demo"] = "效果预览（与本程序同一条渲染管线）",
            ["tutorial.insert"] = "插入到编辑器",
            ["tutorial.inserted"] = "已插入到你当前光标的位置",
            ["tutorial.no.editor"] = "没有打开的文档，请先新建或打开一个文档。",
            ["tutorial.prev"] = "上一课",
            ["tutorial.next"] = "下一课",
            ["tutorial.tab.lesson"] = "课程与练习",
            ["tutorial.tab.quiz"] = "结业测试",
            ["tutorial.practice"] = "动手练习",
            ["tutorial.practice.insert"] = "插入起始片段",
            ["tutorial.practice.check"] = "校验我的写法",
            ["tutorial.practice.answer"] = "看参考答案",
            ["tutorial.practice.passed"] = "✓ 全部通过，这一课完成了。",
            ["tutorial.practice.failed"] = "还差 {0} 项没通过：请照着下面的清单逐条改。",
            ["tutorial.practice.noeditor"] = "没有可校验的文档：请先把「起始片段」插入编辑器，改好后再来校验。",
            ["tutorial.practice.note"] = "参考要点",
            ["tutorial.practice.answerlabel"] = "参考答案",
            ["tutorial.practice.done"] = "本课练习已完成",
            ["tutorial.quiz.title"] = "结业测试",
            ["tutorial.quiz.subtitle"] = "覆盖各课的必记要点；答对 {0} 题即通过。",
            ["tutorial.quiz.submit"] = "交卷",
            ["tutorial.quiz.retake"] = "重做一遍",
            ["tutorial.quiz.score"] = "得分 {0} · 答对 {1} / {2} 题",
            ["tutorial.quiz.passed"] = "通过！可以开始写自己的文档了。",
            ["tutorial.quiz.failed"] = "未通过：把下面标红的题目对应的课程再读一遍，然后重做。",
            ["tutorial.quiz.best"] = "历史最好成绩：{0} 分",
            ["tutorial.quiz.unanswered"] = "未作答",
            ["tutorial.quiz.right"] = "✓ 正确",
            ["tutorial.quiz.wrong"] = "✗ 答错（正确选项：{0}）",
            ["tutorial.quiz.why"] = "解析",

            // ───────────────────────── 启动界面 ─────────────────────────
            ["splash.loading"] = "正在装载界面…",
            ["splash.version"] = "版本 {0}",

            // ───────────────────────── 打印 ─────────────────────────
            ["print.title"] = "打印预览",
            ["print.page"] = "第 {0} / {1} 页",
            ["print.header"] = "页眉（文档标题）",
            ["print.footer"] = "页脚（页码）",
            ["print.paper"] = "纸张",
            ["print.paper.a4"] = "A4",
            ["print.paper.a5"] = "A5",
            ["print.paper.letter"] = "Letter",
            ["print.orientation"] = "方向",
            ["print.orientation.portrait"] = "纵向",
            ["print.orientation.landscape"] = "横向",
            ["print.margin"] = "页边距",
            ["print.margin.narrow"] = "窄",
            ["print.margin.normal"] = "常规",
            ["print.margin.wide"] = "宽",
            ["print.monochrome"] = "黑白打印（省墨）",
            ["print.do"] = "打印…",
            ["print.prev"] = "上一页",
            ["print.next"] = "下一页",
            ["print.missing"] = "当前没有可打印的文档。",
            ["print.dialog.title"] = "打印",

            // ───────────────────────── 关于 ─────────────────────────
            ["about.title"] = "关于",
            ["about.tagline"] = "写文档、看文档，都在同一个窗口里完成。",
            ["about.credit"] = "编写：软体程式部　评议通过：专家委员会",
            ["about.version"] = "版本 {0}",
            ["about.spec"] = "符合 PRT v{0} EXT 等级 · 不实现 COMP（受限计算）",
            ["about.feature.title"] = "功能一览",
            ["about.feature.1"] = "左边写、右边看：点哪一边，另一边自动跳到对应位置并高亮",
            ["about.feature.2"] = "标题、列表、表格、提示框、图片、按钮等常用写法都支持",
            ["about.feature.3"] = "能打开 .prt 文档与 .md 文件，也能把网页（HTML）转成文档",
            ["about.feature.4"] = "界面全部原生绘制，不使用 WebView 或任何浏览器内核",
            ["about.feature.5"] = "按 F1 打开随程序附带的《PRT 教程》，边做边学",
            ["about.license.title"] = "当前授权",
            ["about.license.hint"] = "授权只保存在程序同级目录；本机其他副本各自独立，互不影响。",
            ["about.button.compliance"] = "符合性声明",
            ["about.button.shortcuts"] = "快捷键",
            ["about.button.activation"] = "激活与授权…",

            // ───────────────────────── 激活 ─────────────────────────
            ["activation.title"] = "激活与授权",
            ["activation.subtitle"] = "离线激活 · RSA-2048 签名校验 · 全程不联网",
            ["activation.section.current"] = "当前授权",
            ["activation.section.issuer"] = "签发明细",
            ["activation.section.levels"] = "等级与权益",
            ["activation.section.code"] = "激活码",
            ["activation.code.hint"] = "由供应商离线签发，含用户名、邮箱、等级与有效期；整行粘贴即可。",
            ["activation.badge.none"] = "未激活",
            ["activation.badge.vip"] = "VIP",
            ["activation.issued.at"] = "签发时间",
            ["activation.quota"] = "授权量",
            ["activation.quota.value"] = "{0} 台设备",
            ["activation.issuer"] = "签发人",
            ["activation.reason"] = "签发理由",
            ["activation.used"] = "本副本已激活 {0} 次",
            ["activation.seats.exceeded"] = "授权量 {0} 台 · 本副本已激活 {1} 次（已超出授权量，请核对是否在多台设备上重复激活）",
            ["activation.file"] = "授权文件",
            ["activation.file.hint"] = "{0}（只对本副本生效，本机其他副本不受影响）",
            ["activation.paste"] = "粘贴",
            ["activation.clear"] = "清空",
            ["activation.activate"] = "激活",
            ["activation.message.ok"] = "激活成功：{0} <{1}> · {2} · {3}",
            ["activation.message.seats"] = " · 授权量 {0} 台",
            ["activation.message.used"] = " · 本副本已激活 {0} 次",
            ["activation.message.notsaved"] = "激活本次运行已生效，但授权文件写入失败，重启后会恢复为未激活。{0}",
            ["activation.message.failed"] = "激活失败：{0}",
            ["activation.level.free"] = "Free",
            ["activation.level.free.suffix"] = "（免费）",
            ["activation.level.free.desc"] = "最多 2 个标签页；导出仅纯文本",
            ["activation.level.vip"] = "VIP",
            ["activation.level.vip.suffix"] = "（限时）",
            ["activation.level.vip.desc"] = "限时激活码在界面上显示为 VIP：按到期日享有标准或专业权益",
            ["activation.level.perpetual"] = "永久授权",
            ["activation.level.perpetual.desc"] = "永久码显示签发等级：Standard（标准）/ Professional（专业，全部功能）",
            ["activation.none"] = "（未填写）",

            // ───────────────────────── 授权摘要（状态栏 / 关于 / 激活） ─────────────────────────
            ["license.level.free"] = "Free（免费版）：最多 2 个标签页，导出仅纯文本",
            ["license.level.standard"] = "Standard（标准版）：标签页数量不限，导出 HTML / 纯文本。限时激活码在界面上显示为 VIP",
            ["license.level.professional"] = "Professional（专业版）：全部功能（标签页不限，导出 HTML / Markdown / 纯文本）。限时激活码在界面上显示为 VIP",
            ["license.expiry.perpetual"] = "永久有效",
            ["license.expiry.date"] = "有效期至 {0}",
            ["license.summary.issuer"] = "签发人 {0}",
        };

    /// <summary>英文词条（键集合必须与中文表一致）。</summary>
    internal static readonly IReadOnlyDictionary<string, string> En =
        new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            // ───────────────────────── Common ─────────────────────────
            ["app.name"] = "PRT Reader",
            ["common.ok"] = "OK",
            ["common.cancel"] = "Cancel",
            ["common.close"] = "Close",
            ["common.reset"] = "Restore default",
            ["common.browse"] = "Browse…",
            ["common.refresh"] = "Refresh",
            ["common.yes"] = "Yes",
            ["common.no"] = "No",

            // ───────────────────────── Caption bar ─────────────────────────
            ["caption.minimize"] = "Minimize",
            ["caption.maximize"] = "Maximize",
            ["caption.restore"] = "Restore",
            ["caption.close"] = "Close",

            // ───────────────────────── Menu: File ─────────────────────────
            ["menu.file"] = "File",
            ["menu.file.new"] = "New",
            ["menu.file.open"] = "Open…",
            ["menu.file.save"] = "Save",
            ["menu.file.saveas"] = "Save as…",
            ["menu.file.reload"] = "Reload",
            ["menu.file.closetab"] = "Close tab",
            ["menu.file.closeall"] = "Close all tabs",
            ["menu.file.export.html"] = "Export as HTML…",
            ["menu.file.export.markdown"] = "Export as Markdown…",
            ["menu.file.export.text"] = "Export as plain text…",
            ["menu.file.import.html"] = "New document from HTML…",
            ["menu.file.import.html.tip"] = "Convert HTML exported from a web page or Word into a PRT document (opens in a new tab)",
            ["menu.file.print"] = "Print…",
            ["menu.file.exit"] = "Exit",

            // ───────────────────────── Menu: Edit ─────────────────────────
            ["menu.edit"] = "Edit",
            ["menu.edit.undo"] = "Undo",
            ["menu.edit.redo"] = "Redo",
            ["menu.edit.cut"] = "Cut",
            ["menu.edit.copy"] = "Copy",
            ["menu.edit.paste"] = "Paste",
            ["menu.edit.selectline"] = "Select current line",
            ["menu.edit.find"] = "Find…",
            ["menu.edit.replace"] = "Replace…",
            ["menu.edit.selectall"] = "Select all",

            // ───────────────────────── Menu: Insert / View ─────────────────────────
            ["menu.insert"] = "Insert",
            ["menu.insert.semantic"] = "Callouts (13 kinds)",
            ["menu.insert.structure"] = "Structure blocks",
            ["menu.insert.basic"] = "Basic blocks",
            ["menu.view"] = "View",
            ["menu.view.mode.editor"] = "Source only",
            ["menu.view.mode.split"] = "Split (source + visual editing)",
            ["menu.view.mode.preview"] = "Visual editing",
            ["menu.view.outline"] = "Show outline panel",
            ["menu.view.problems"] = "Show diagnostics panel",
            ["menu.view.wordwrap"] = "Wrap long lines in the editor",
            ["menu.view.zoomin"] = "Zoom in",
            ["menu.view.zoomout"] = "Zoom out",
            ["menu.view.zoomreset"] = "Reset zoom",
            ["menu.view.strict"] = "Force strict mode (ignore the document's strict declaration)",

            // ───────────────────────── Menu: Theme ─────────────────────────
            ["menu.theme"] = "Theme",
            ["menu.theme.interface"] = "Interface colors",
            ["menu.theme.interface.light"] = "Light",
            ["menu.theme.interface.dark"] = "Dark",
            ["menu.theme.preview"] = "Preview theme (PRT themes, specification chapter 12)",
            ["menu.theme.preview.follow"] = "Follow the document",
            ["menu.theme.preview.default"] = "default",
            ["menu.theme.preview.dark"] = "dark",
            ["menu.theme.preview.print"] = "print",
            ["menu.theme.preview.accessible"] = "accessible",

            // ───────────────────────── Menu: Settings / Help ─────────────────────────
            ["menu.settings"] = "Settings",
            ["menu.settings.general"] = "Preferences…",
            ["menu.settings.tutorial"] = "Open the tutorial (built in)",
            ["menu.settings.authorguide"] = "Open the author guide (built in)",
            ["menu.help"] = "Help",
            ["menu.help.sample"] = "Open the sample document…",
            ["menu.help.activation"] = "Activation…",
            ["menu.help.compliance"] = "Conformance statement…",
            ["menu.help.security"] = "Security Center…",
            ["menu.help.shortcuts"] = "Keyboard shortcuts…",
            ["menu.help.about"] = "About…",

            // ───────────────────────── Command bar ─────────────────────────
            ["toolbar.new"] = "New",
            ["toolbar.new.tip"] = "New document (Ctrl+N)",
            ["toolbar.open"] = "Open",
            ["toolbar.open.tip"] = "Open a document (Ctrl+O)",
            ["toolbar.save"] = "Save",
            ["toolbar.save.tip"] = "Save (Ctrl+S)",
            ["toolbar.undo.tip"] = "Undo (Ctrl+Z)",
            ["toolbar.redo.tip"] = "Redo (Ctrl+Y)",
            ["toolbar.find"] = "Find",
            ["toolbar.find.tip"] = "Find (Ctrl+F)",
            ["toolbar.replace"] = "Replace",
            ["toolbar.replace.tip"] = "Replace (Ctrl+H)",
            ["toolbar.mode.source"] = "Source",
            ["toolbar.mode.split"] = "Split",
            ["toolbar.mode.preview"] = "Visual",
            ["toolbar.outline"] = "Outline",
            ["toolbar.outline.tip"] = "Show / hide the outline panel",
            ["toolbar.problems"] = "Issues",
            ["toolbar.problems.tip"] = "Show / hide the diagnostics panel",
            ["toolbar.export.html.tip"] = "Export as an HTML file",
            ["toolbar.export.markdown.tip"] = "Export as a Markdown file",
            ["toolbar.export.text"] = "Text",
            ["toolbar.export.text.tip"] = "Export as a plain-text file",
            ["toolbar.print"] = "Print",
            ["toolbar.print.tip"] = "Print (Ctrl+P)",

            // ───────────────────────── Panels ─────────────────────────
            ["panel.outline"] = "Outline",
            ["panel.problems"] = "Diagnostics",

            // ───────────────────────── Status bar ─────────────────────────
            ["status.ready"] = "Ready",
            ["status.position"] = "Line {0}, column {1}",
            ["status.chars"] = "{0} characters",
            ["status.diagnostics"] = "{0} errors · {1} warnings",
            ["status.mode.editor"] = "Source",
            ["status.mode.split"] = "Split",
            ["status.mode.preview"] = "Visual",
            ["status.interface.dark"] = "Interface colors: dark",
            ["status.interface.light"] = "Interface colors: light",
            ["status.zoom"] = "Zoom: {0}%",
            ["status.wordwrap.on"] = "Line wrapping enabled",
            ["status.wordwrap.off"] = "Line wrapping disabled",
            ["status.strict.forced"] = "Strict mode forced: the document's strict declaration is ignored",
            ["status.strict.follow"] = "Strict mode: follows the document (strict when not declared)",
            ["status.previewtheme"] = "Preview theme: {0}",
            ["status.previewtheme.follow"] = "Preview theme: follow the document",
            ["status.settings.applied"] = "Settings applied",
            ["status.settings.preview"] = "Previewing settings (press OK to keep them)",
            ["status.settings.reverted"] = "Settings changes discarded",
            ["status.language.restart"] = "Language changed; restart the app to apply it everywhere",
            ["status.splash.updated"] = "Startup image updated",
            ["status.splash.reset"] = "Built-in startup image restored",
            ["status.print.done"] = "Sent to the printer",
            ["status.print.cancelled"] = "Printing cancelled",
            ["status.bundled.missing"] = "{0} — please check that the Help folder in the installation directory is complete.",
            ["status.bundled.opened"] = "Opened the built-in {0}: {1}",
            ["status.bundled.switched"] = "Switched to the open {0}",
            ["doc.authorguide"] = "author guide",
            ["doc.authorguide.missing"] = "The built-in PRT author guide was not found",
            ["status.tutorial.opened"] = "Tutorial opened: pick a lesson on the left, then read, try and watch the result",
            ["status.conformance"] = "PRT v{0} · EXT (COMP unsupported)",
            ["status.comp.degraded"] = " · COMP degraded",

            // ───────────────────────── Settings window ─────────────────────────
            ["settings.title"] = "Settings",
            ["settings.footer"] = "Changes take effect at once (preview). Press OK to keep them; Cancel or closing the window restores the previous state.",
            ["settings.tab.appearance"] = "Appearance",
            ["settings.tab.editor"] = "Editing",
            ["settings.tab.startup"] = "Startup & language",
            ["settings.interface"] = "Interface colors",
            ["settings.interface.light"] = "Light",
            ["settings.interface.dark"] = "Dark",
            ["settings.interface.hint"] = "Affects the app shell (menus, panels). The preview follows the interface colors unless the document declares its own theme.",
            ["settings.previewtheme"] = "Document appearance (preview theme)",
            ["settings.previewtheme.follow"] = "Follow the document (otherwise follow the interface)",
            ["settings.previewtheme.default"] = "Default (light)",
            ["settings.previewtheme.dark"] = "Dark",
            ["settings.previewtheme.print"] = "Print (monochrome)",
            ["settings.previewtheme.accessible"] = "Accessible (high readability)",
            ["settings.previewtheme.hint"] = "Only changes how documents look; the file itself is never modified.",
            ["settings.zoom"] = "Zoom",
            ["settings.wordwrap"] = "Wrap long lines in the editor (no line breaks are inserted)",
            ["settings.strict"] = "Strict validation (report any problem as an error)",
            ["settings.strict.hint"] = "By default the reader is lenient: what it understands is rendered, the rest is kept as-is. Enable strict mode to fail fast — useful before a final review.",
            ["settings.viewmode"] = "Default view",
            ["settings.viewmode.editor"] = "Source only",
            ["settings.viewmode.split"] = "Split",
            ["settings.viewmode.preview"] = "Visual only",
            ["settings.viewmode.hint"] = "The view used for new documents and at startup. You can switch at any time from the toolbar or the View menu.",
            ["settings.splash.enable"] = "Show a startup screen",
            ["settings.splash.image"] = "Startup image",
            ["settings.splash.builtin"] = "Built-in image",
            ["settings.splash.hint"] = "PNG / JPG / BMP; a landscape image around 2:1 (e.g. 640×320) works best. The image is copied into the folder the app lives in, so moving or deleting the original file is harmless.",
            ["settings.language"] = "Interface language",
            ["settings.language.system"] = "Follow the system",
            ["settings.language.zh"] = "简体中文",
            ["settings.language.en"] = "English",
            ["settings.language.hint"] = "Menus and dialogs fully switch to the new language the next time the app starts.",
            ["settings.defaultview.changed"] = "Default view: {0}",
            ["settings.splash.failed"] = "Could not set the startup image: {0}",
            ["settings.save.failed"] = "Settings could not be saved: {0}",

            // ───────────────────────── Tutorial window ─────────────────────────
            ["tutorial.title"] = "Tutorial",
            ["tutorial.subtitle"] = "Learn by doing: pick a lesson on the left, read, try, and watch the result",
            ["tutorial.lessons"] = "Lessons",
            ["tutorial.progress"] = "Lesson {0} of {1}",
            ["tutorial.snippet"] = "This lesson's example (can be inserted)",
            ["tutorial.demo"] = "Rendered result (same pipeline as the app)",
            ["tutorial.insert"] = "Insert into the editor",
            ["tutorial.inserted"] = "Inserted at your caret",
            ["tutorial.no.editor"] = "No document is open — create or open one first.",
            ["tutorial.prev"] = "Previous",
            ["tutorial.next"] = "Next",
            ["tutorial.tab.lesson"] = "Lessons & practice",
            ["tutorial.tab.quiz"] = "Final test",
            ["tutorial.practice"] = "Hands-on practice",
            ["tutorial.practice.insert"] = "Insert the starting snippet",
            ["tutorial.practice.check"] = "Check my writing",
            ["tutorial.practice.answer"] = "Show the answer",
            ["tutorial.practice.passed"] = "✓ All checks passed — this lesson is complete.",
            ["tutorial.practice.failed"] = "{0} check(s) still failing — fix them one by one.",
            ["tutorial.practice.noeditor"] = "Nothing to check: insert the starting snippet into the editor first, then edit it and come back.",
            ["tutorial.practice.note"] = "Key points",
            ["tutorial.practice.answerlabel"] = "Answer",
            ["tutorial.practice.done"] = "Practice completed",
            ["tutorial.quiz.title"] = "Final test",
            ["tutorial.quiz.subtitle"] = "Covers the must-remember points of every lesson; pass with {0} correct.",
            ["tutorial.quiz.submit"] = "Submit",
            ["tutorial.quiz.retake"] = "Retake",
            ["tutorial.quiz.score"] = "Score {0} · {1} of {2} correct",
            ["tutorial.quiz.passed"] = "Passed! You are ready to write your own documents.",
            ["tutorial.quiz.failed"] = "Not passed — reread the lessons behind the questions marked in red, then retake.",
            ["tutorial.quiz.best"] = "Best score so far: {0}",
            ["tutorial.quiz.unanswered"] = "Not answered",
            ["tutorial.quiz.right"] = "✓ correct",
            ["tutorial.quiz.wrong"] = "✗ wrong (correct option: {0})",
            ["tutorial.quiz.why"] = "Why",

            // ───────────────────────── Startup screen ─────────────────────────
            ["splash.loading"] = "Loading the interface…",
            ["splash.version"] = "Version {0}",

            // ───────────────────────── Printing ─────────────────────────
            ["print.title"] = "Print preview",
            ["print.page"] = "Page {0} of {1}",
            ["print.header"] = "Header (document title)",
            ["print.footer"] = "Footer (page number)",
            ["print.paper"] = "Paper",
            ["print.paper.a4"] = "A4",
            ["print.paper.a5"] = "A5",
            ["print.paper.letter"] = "Letter",
            ["print.orientation"] = "Orientation",
            ["print.orientation.portrait"] = "Portrait",
            ["print.orientation.landscape"] = "Landscape",
            ["print.margin"] = "Margins",
            ["print.margin.narrow"] = "Narrow",
            ["print.margin.normal"] = "Normal",
            ["print.margin.wide"] = "Wide",
            ["print.monochrome"] = "Monochrome (saves ink)",
            ["print.do"] = "Print…",
            ["print.prev"] = "Previous",
            ["print.next"] = "Next",
            ["print.missing"] = "There is no document to print.",
            ["print.dialog.title"] = "Print",

            // ───────────────────────── About ─────────────────────────
            ["about.title"] = "About",
            ["about.tagline"] = "Write and read documents in one and the same window.",
            ["about.credit"] = "Developed by the Software Department · Approved by the Expert Committee",
            ["about.version"] = "Version {0}",
            ["about.spec"] = "Complies with PRT v{0} EXT · COMP (restricted computation) not implemented",
            ["about.feature.title"] = "Highlights",
            ["about.feature.1"] = "Write on the left, read on the right: clicking either side jumps to and highlights the matching position",
            ["about.feature.2"] = "Headings, lists, tables, callouts, images and buttons are all supported",
            ["about.feature.3"] = "Opens .prt documents and .md files, and converts web pages (HTML) into documents",
            ["about.feature.4"] = "Everything is rendered natively — no WebView or browser engine",
            ["about.feature.5"] = "Press F1 for the bundled PRT tutorial and learn by doing",
            ["about.license.title"] = "Current license",
            ["about.license.hint"] = "The license is kept next to the executable; other copies on this machine stay independent.",
            ["about.button.compliance"] = "Conformance statement",
            ["about.button.shortcuts"] = "Shortcuts",
            ["about.button.activation"] = "Activation…",

            // ───────────────────────── Activation ─────────────────────────
            ["activation.title"] = "Activation and licensing",
            ["activation.subtitle"] = "Offline activation · RSA-2048 signature check · No network access",
            ["activation.section.current"] = "Current license",
            ["activation.section.issuer"] = "Issuer details",
            ["activation.section.levels"] = "Editions and benefits",
            ["activation.section.code"] = "Activation code",
            ["activation.code.hint"] = "Issued offline by the supplier with user name, e-mail, edition and expiry; paste the whole line.",
            ["activation.badge.none"] = "Not activated",
            ["activation.badge.vip"] = "VIP",
            ["activation.issued.at"] = "Issued",
            ["activation.quota"] = "Seats",
            ["activation.quota.value"] = "{0} device(s)",
            ["activation.issuer"] = "Issued by",
            ["activation.reason"] = "Reason",
            ["activation.used"] = "Activated {0} time(s) in this copy",
            ["activation.seats.exceeded"] = "Seats {0} · activated {1} time(s) in this copy (beyond the licensed count — check for repeat activation on several machines)",
            ["activation.file"] = "License file",
            ["activation.file.hint"] = "{0} (applies to this copy only; other copies on this machine are unaffected)",
            ["activation.paste"] = "Paste",
            ["activation.clear"] = "Clear",
            ["activation.activate"] = "Activate",
            ["activation.message.ok"] = "Activated: {0} <{1}> · {2} · {3}",
            ["activation.message.seats"] = " · {0} device(s)",
            ["activation.message.used"] = " · activated {0} time(s) in this copy",
            ["activation.message.notsaved"] = "Active for this session, but the license file could not be written; activation will be lost after a restart. {0}",
            ["activation.message.failed"] = "Activation failed: {0}",
            ["activation.level.free"] = "Free",
            ["activation.level.free.suffix"] = "(free)",
            ["activation.level.free.desc"] = "Up to 2 tabs; plain-text export only",
            ["activation.level.vip"] = "VIP",
            ["activation.level.vip.suffix"] = "(time-limited)",
            ["activation.level.vip.desc"] = "Time-limited codes show as VIP: Standard or Professional benefits until the expiry date",
            ["activation.level.perpetual"] = "Perpetual",
            ["activation.level.perpetual.desc"] = "Perpetual codes show the issued edition: Standard or Professional (all features)",
            ["activation.none"] = "(not specified)",

            // ───────────────────────── License summary (status bar / About / Activation) ─────────────────────────
            ["license.level.free"] = "Free: up to 2 tabs, plain-text export only",
            ["license.level.standard"] = "Standard: unlimited tabs, export to HTML / plain text. Time-limited codes are shown as VIP",
            ["license.level.professional"] = "Professional: all features (unlimited tabs, export to HTML / Markdown / plain text). Time-limited codes are shown as VIP",
            ["license.expiry.perpetual"] = "Perpetual",
            ["license.expiry.date"] = "valid until {0}",
            ["license.summary.issuer"] = "issued by {0}",
        };
}
